---
- hosts: all
  become: yes
  vars: 
    remote_user: ec2-user
    ansible_ssh_private_key_file: dynamic_inventory_key.pem

  tasks:
    - name: pinging the target host
      ping: 
        
    - name: printing something
      debug: 
       msg: "This is testing awx-aws"     
